### ISSUE TITLE
Allow to configure where Kanbn files are stored

### ISSUE THREAD

**Issue by ngirard** [basementuniverse/vscode-kanbn#2]
As a follow-up to #1, I found counterintuitive that Kanbn's markdown files were buried into a hidden directory.

First, because their contents are of equal importance than the rest of the workspace they're lying into, so by following the [hierarchy of information](https://www.bridgewaterlearning.co.za/2013/04/16/design-principles-hierarchy-of-information/)(*), these files should be as much visible as the others.

Next, because -- unless I'm misunderstood, the design decision behind choosing Markdown as a backend is to allow people to easily modify their tasks-related data from within the Markdown files.

Finally, in the scenario I briefly mentioned, which is to integrate Kanbn and [Markdown Memo](https://github.com/svsool/vscode-memo), it would make more sense if all the markdown files of a project are gathered into a single (not hidden) directory.

(*) I blindlessly pasted the first result from my google search. I'm sure about the value of the principle, not so much about the quality of the article.

**Comment by basementuniverse** [comment]
That's a good point about information hierarchy - especially since in the documentation I've emphasised the ease of viewing and editing the markdown files by hand, perhaps putting them in a hidden folder is rather counterintuitive.

I'd prefer to make the Kanbn root path configurable, with a default setting that is 'good enough' for most users. This is something that I already implemented in a very early version of Kanbn, but it got scrapped somewhere along the line...

There needs to be a single well-known entry-point so that the [Kanbn CLI](https://github.com/basementuniverse/kanbn) app can find the index and tasks, but this can be achieved like so:

* Kanbn will look for `./kanbnconfig.json` (or `.yml`) which should contain a setting `"rootPath"`
* If this file doesn't exist or it doesn't have a `"rootPath"` setting, use the default directory `./.kanbn`

This config file could also include configuration for where to find the index file (maybe allowing us to have multiple indexes per workspace in the future), where to find the tasks, etc.

Also, because a lot of people will be using the [VSCode extension](https://github.com/basementuniverse/vscode-kanbn) and not the [CLI app](https://github.com/basementuniverse/kanbn) (even though the extension is really just a wrapper around the CLI app functionality), I could add these configuration settings directly to VSCode settings as well. This means users won't need yet-another config file hanging around.

**Comment by ngirard** [comment]
Seems perfect, please go ahead !

**Comment by basementuniverse** [comment]
A quick update: I've got a [branch in progress](https://github.com/basementuniverse/kanbn/tree/configurable-entry-point) that should address this. It will allow users to create a `kanbn.json` / `kanbn.yml` config file in the workspace root, and in this file we can configure the Kanbn directory name, index filename, tasks folder etc...

**Comment by basementuniverse** [comment]
Implemented in [0.6.0](https://github.com/basementuniverse/vscode-kanbn/commit/8a2726a486ee499acc5670c4b72733e874c89034)

**Comment by lonix1** [comment]
@basementuniverse In vscode the convention is to store config files in the `.vscode/` directory. Would it be possible to add that as another search location?

Then we could use `.vscode/kanbn.json`.
